spring.application.name=New-mongodb-project
API.Creation_successful=User successfully added
Service.Employee.NotFound=User is not found of this id
Service.Employee.Found=User is present already
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/employeedb

# Logging Level
logging.level.root=INFO

# Package Specific Logging
logging.level.com.example.New.mongodb.project=DEBUG

# Log Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


server.port=8080
